# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [3]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)


ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.95930411 0.42864157 0.2173572  ... 0.4913273  0.27461162 0.63871789]
 [0.50950065 0.33086916 0.91387903 ... 0.56427192 0.48385316 0.11752575]
 [0.90622787 0.00175115 0.16628989 ... 0.18792272 0.65965031 0.53734769]
 ...
 [0.51099031 0.6051206  0.21260948 ... 0.39651535 0.85195402 0.63160405]
 [0.60978099 0.03656025 0.36735894 ... 0.26537927 0.09524309 0.6040576 ]
 [0.29167536 0.15140363 0.38341854 ... 0.14707997 0.40885354 0.07807116]]
[[0.31122757 0.69595747 0.17297818 ... 0.82551887 0.64920427 0.34384715]
 [0.64215597 0.66067957 0.92663221 ... 0.40660385 0.4618518  0.7795241 ]
 [0.05005164 0.51143344 0.70244321 ... 0.46627161 0.93426938 0.80135956]
 ...
 [0.11563235 0.23384916 0.96226127 ... 0.82952045 0.50930713 0.88608691]
 [0.51744706 0.43628927 0.2702167  ... 0.55134004 0.86294736 0.27999581]
 [0.58228282 0.83222768 0.89392393 ... 0.85477081 0.70491637 0.00532809]]


Без использования numpy

In [9]:
def mult(a, b):
  result = []
  for i in range(len(a)):
    row = []
    for j in range(len(b[0])):
      sum = 0
      for k in range(len(b)):
        sum += a[i][k] * b[k][j]
      row.append(sum)
    result.append(row)
  return result

In [ ]:
mult(a, b)

C использованием numpy

In [7]:
def np_mult(a, b):
  result = np.dot(a, b)
  return result

In [ ]:
np_mult(a, b)

In [11]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 666 ms, sys: 2.33 ms, total: 669 ms
Wall time: 678 ms


In [12]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.28 ms, sys: 1.04 ms, total: 2.32 ms
Wall time: 2.74 ms


In [13]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.4996004438216914e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [14]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.44584454 0.6935815  0.08097208] [0.99696696 0.56483435 0.6468786 ]


In [15]:
def scalar_product(a, b):
  s = sum(i*j for i, j in zip(a, b))
  return s

In [16]:
def np_scalar_product(a, b):
  s = np.dot(a, b)
  return s

In [17]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 35 µs, sys: 0 ns, total: 35 µs
Wall time: 38.9 µs
CPU times: user 160 µs, sys: 0 ns, total: 160 µs
Wall time: 734 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Numpy эффективнее так как он реализован на C.
Numpy использует оптимизированные алгоритмы, написанные на компилируемых языках, которые быстрее, чем интерпретируемый Python

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [18]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diag = np.diagonal(a)
  even_diag = diag[diag % 2 == 0]
  if len(even_diag) == 0:
    return 0
  else:
    return np.sum(even_diag)

In [19]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 3, 2, 1, 4],
       [6, 3, 9, 4, 8],
       [9, 4, 6, 6, 8],
       [6, 2, 2, 4, 5],
       [7, 4, 1, 9, 2]])

In [20]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 158 µs, sys: 20 µs, total: 178 µs
Wall time: 183 µs


12

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [21]:
def np_sec_av(*A):
  result = []
  for a in A:
    flattened = np.unique(a.ravel())
    if len(flattened) > 1:
      result.append(np.partition(flattened, 1)[1])
    else:
      result.append(None)
  return result

In [22]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[3.39079980e-01 2.64627246e-01 2.65679892e-01 8.05964313e-02
 3.95888332e-01 6.27759786e-01 9.12854085e-01 7.29886775e-01
 1.43783119e-01 6.70532388e-01 4.37465473e-01 2.74128029e-01
 9.41330811e-01 7.10163105e-01 8.81005517e-02 8.77188142e-01
 8.49765529e-01 5.22697058e-02 6.12928801e-01 3.74118111e-01
 9.55785902e-01 1.16111782e-01 2.37105555e-01 6.91499973e-01
 8.78971609e-01 3.16438915e-01 9.44460140e-01 9.76207045e-01
 7.53647059e-01 2.75635755e-01 7.51338240e-01 9.73812938e-01
 4.76090808e-03 2.45690631e-01 5.01846778e-01 8.05364727e-01
 6.59980700e-01 2.36177504e-01 3.67124210e-01 5.43009920e-01
 2.08781220e-01 2.72575432e-03 9.21320623e-01 4.99536042e-02
 8.61037277e-01 6.02852058e-01 9.06908080e-01 2.21518578e-01
 7.63452364e-02 9.69442415e-01 3.71270406e-01 9.88778282e-01
 4.00841691e-01 5.30534533e-01 3.70463225e-01 4.47253398e-01
 3.22150065e-01 9.02600305e-01 3.69202089e-01 4.98206229e-01
 8.10434206e-02 3.52095209e-01 5.75896572e-01 1.60443344e-01
 3.11895640e-02 7.665798

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [23]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
  unique_elements, counts = np.unique(a, return_counts=True) # находим уникальные элементы и их количество
  return unique_elements, counts

In [24]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 271 µs, sys: 0 ns, total: 271 µs
Wall time: 280 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [25]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
  modified_X = np.copy(X)
  modified_X[1::2] = a
  modified_X[0::2] = np.power(modified_X[0::2], 3)
  result = np.concatenate((X, modified_X[::-1]))
  return result

In [26]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 201 µs, sys: 26 µs, total: 227 µs
Wall time: 333 µs
